# These are supported funding model platforms

github: [nirholas]
# patreon: 
# open_collective: 
# ko_fi: 
# tidelift: 
# community_bridge: 
# liberapay: 
# issuehunt: 
# lfx_crowdfunding: 
# polar: 
